import json

phrases = [
    ("a great deal of", "a lot of"),
    ("account for", "explain"),
    ("a wide range of", "a large variety of"),
    ("adapt to", "get used to"),
    ("adhere to", "stick to"),
    ("agree with", "consent to"),
    ("apart from", "except for"),
    ("apply for", "request"),
    ("as a result of", "due to"),
    ("as well as", "in addition to"),
    ("at the expense of", "at the cost of"),
    ("attribute to", "ascribe to"),
    ("be capable of", "be able to"),
    ("be composed of", "consist of"),
    ("be concerned with", "be related to"),
    ("be dependent on", "rely on"),
    ("be derived from", "stem from"),
    ("be eager to", "be anxious to"),
    ("be engaged in", "be involved in"),
    ("be equivalent to", "be equal to"),
    ("be essential for", "be vital for"),
    ("be exposed to", "be subjected to"),
    ("be familiar with", "be acquainted with"),
    ("be forced to", "be compelled to"),
    ("be identical to", "be the same as"),
    ("be ignorant of", "be unaware of"),
    ("be inclined to", "tend to"),
    ("be indifferent to", "turn a blind eye to"),
    ("be indispensable for", "be crucial for"),
    ("be inferior to", "be worse than"),
    ("be liable to", "be prone to"),
    ("be linked to", "be associated with"),
    ("be opposed to", "be against"),
    ("be prior to", "be before"),
    ("be reluctant to", "be unwilling to"),
    ("be responsible for", "be in charge of"),
    ("be restricted to", "be limited to"),
    ("be satisfied with", "be content with"),
    ("be sensitive to", "be susceptible to"),
    ("be similar to", "be akin to"),
    ("be subject to", "be vulnerable to"),
    ("be superior to", "be better than"),
    ("be supposed to", "be expected to"),
    ("be suspicious of", "be skeptical of"),
    ("be typical of", "be characteristic of"),
    ("be used to", "be accustomed to"),
    ("be willing to", "be ready to"),
    ("bear in mind", "keep in mind"),
    ("benefit from", "profit from"),
    ("blame for", "hold responsible for"),
    ("bring about", "lead to"),
    ("by means of", "by way of"),
    ("by no means", "in no way"),
    ("call for", "require"),
    ("carry out", "implement"),
    ("catch up with", "keep pace with"),
    ("come across", "run into"),
    ("come up with", "think of"),
    ("comment on", "remark on"),
    ("compensate for", "make up for"),
    ("comply with", "conform to"),
    ("concentrate on", "focus on"),
    ("contribute to", "play a part in"),
    ("cope with", "deal with"),
    ("cut down on", "reduce"),
    ("date back to", "originate from"),
    ("depend on", "rely on"),
    ("deprive of", "strip of"),
    ("devote to", "dedicate to"),
    ("die out", "become extinct"),
    ("differ from", "be distinct from"),
    ("dispose of", "get rid of"),
    ("distinguish between", "differentiate between"),
    ("do away with", "eliminate"),
    ("draw attention to", "highlight"),
    ("drop out of", "quit"),
    ("due to", "because of"),
    ("embark on", "start"),
    ("end up with", "result in"),
    ("engage in", "participate in"),
    ("exert influence on", "have an impact on"),
    ("fall short of", "fail to reach"),
    ("figure out", "work out"),
    ("focus on", "concentrate on"),
    ("for the sake of", "for the benefit of"),
    ("get access to", "gain entry to"),
    ("get accustomed to", "get used to"),
    ("get along with", "get on with"),
    ("get rid of", "eliminate"),
    ("give priority to", "put first"),
    ("give rise to", "cause"),
    ("go hand in hand with", "be closely connected with"),
    ("have a negative impact on", "take a toll on"),
    ("have an effect on", "influence"),
    ("have nothing to do with", "be irrelevant to"),
    ("in accordance with", "in line with"),
    ("in addition to", "besides"),
    ("in advance", "beforehand"),
    ("in behalf of", "on behalf of"),
    ("in charge of", "responsible for"),
    ("in comparison with", "compared to"),
    ("in conflict with", "at odds with"),
    ("in connection with", "in relation to"),
    ("in contrast to", "as opposed to"),
    ("in danger of", "at risk of"),
    ("in exchange for", "in return for"),
    ("in favor of", "in support of"),
    ("in front of", "ahead of"),
    ("in general", "on the whole"),
    ("in light of", "considering"),
    ("in particular", "especially"),
    ("in place of", "instead of"),
    ("in proportion to", "relative to"),
    ("in response to", "in reaction to"),
    ("in search of", "looking for"),
    ("in spite of", "despite"),
    ("in terms of", "regarding"),
    ("in the absence of", "without"),
    ("in the course of", "during"),
    ("in the face of", "confronted with"),
    ("in the long run", "eventually"),
    ("in the meantime", "meanwhile"),
    ("in the wake of", "following"),
    ("in turn", "consequently"),
    ("in vain", "to no avail"),
    ("in view of", "taking into account"),
    ("interfere with", "hinder"),
    ("invest in", "put money into"),
    ("keep an eye on", "monitor"),
    ("keep away from", "stay away from"),
    ("keep in touch with", "maintain contact with"),
    ("keep track of", "keep a record of"),
    ("keep up with", "keep pace with"),
    ("lack of", "shortage of"),
    ("lay emphasis on", "stress"),
    ("lead to", "result in"),
    ("leave behind", "abandon"),
    ("leave out", "omit"),
    ("let alone", "not to mention"),
    ("look back on", "recall"),
    ("look down on", "despise"),
    ("look forward to", "anticipate"),
    ("look into", "investigate"),
    ("look up to", "respect"),
    ("lose track of", "lose sight of"),
    ("make a contribution to", "contribute to"),
    ("make a difference", "have an effect"),
    ("make an effort", "try hard"),
    ("make sense of", "understand"),
    ("make sure", "ensure"),
    ("make up for", "compensate for"),
    ("make use of", "utilize"),
    ("more or less", "to some extent"),
    ("no longer", "not anymore"),
    ("object to", "oppose"),
    ("on account of", "due to"),
    ("on average", "generally"),
    ("on behalf of", "representing"),
    ("on no account", "under no circumstances"),
    ("on purpose", "intentionally"),
    ("on the basis of", "based on"),
    ("on the contrary", "conversely"),
    ("on the other hand", "in contrast"),
    ("on the whole", "generally speaking"),
    ("out of date", "old-fashioned"),
    ("out of order", "broken"),
    ("out of place", "inappropriate"),
    ("out of the question", "impossible"),
    ("owing to", "because of"),
    ("participate in", "take part in"),
    ("pay attention to", "focus on"),
    ("persist in", "insist on"),
    ("point out", "indicate"),
    ("prior to", "before"),
    ("provided that", "on condition that"),
    ("put an end to", "stop"),
    ("put forward", "propose"),
    ("put off", "postpone"),
    ("put up with", "tolerate"),
    ("rather than", "instead of"),
    ("refer to", "mention"),
    ("regardless of", "despite"),
    ("relate to", "connect with"),
    ("rely on", "depend on"),
    ("remind of", "bring to mind"),
    ("resort to", "turn to"),
    ("result from", "arise from"),
    ("result in", "lead to"),
    ("rule out", "exclude"),
    ("run out of", "use up"),
    ("search for", "look for"),
    ("set aside", "save"),
    ("set up", "establish"),
    ("show off", "display proudly"),
    ("show up", "appear"),
    ("speed up", "accelerate"),
    ("stand for", "represent"),
    ("stand out", "be conspicuous"),
    ("stem from", "originate from"),
    ("stick to", "adhere to"),
    ("subject to", "exposed to"),
    ("substitute for", "replace"),
    ("suffer from", "experience"),
    ("sum up", "summarize"),
    ("sympathize with", "feel pity for"),
    ("take advantage of", "utilize"),
    ("take charge of", "be responsible for"),
    ("take for granted", "assume"),
    ("take in", "absorb"),
    ("take into account", "consider"),
    ("take off", "remove"),
    ("take over", "assume control of"),
    ("take part in", "participate in"),
    ("take place", "happen"),
    ("take up", "occupy"),
    ("tend to", "be inclined to"),
    ("think of", "consider"),
    ("throw away", "discard"),
    ("to a large extent", "largely"),
    ("to some extent", "partly"),
    ("turn down", "reject"),
    ("turn into", "transform into"),
    ("turn out", "prove to be"),
    ("turn to", "resort to"),
    ("up to date", "modern"),
    ("use up", "exhaust"),
    ("with regard to", "concerning"),
    ("with respect to", "regarding"),
    ("work out", "figure out"),
    ("yield to", "surrender to"),
    ("abide by", "comply with"),
    ("abstain from", "refrain from"),
    ("accede to", "agree to"),
    ("account to", "explain to"),
    ("acquiesce in", "agree to"),
    ("act on", "take action according to"),
    ("add to", "increase"),
    ("adhere strictly to", "follow closely"),
    ("advise against", "recommend not doing"),
    ("agree on", "reach an agreement about"),
    ("aim at", "target"),
    ("allow for", "take into consideration"),
    ("allude to", "refer indirectly to"),
    ("amount to", "be equivalent to"),
    ("answer for", "be responsible for"),
    ("appeal to", "request earnestly"),
    ("apply to", "be relevant to"),
    ("approve of", "support"),
    ("argue against", "oppose"),
    ("argue for", "support"),
    ("arise from", "result from"),
    ("arrange for", "plan for"),
    ("arrive at", "reach"),
    ("ask for", "request"),
    ("aspire to", "aim for"),
    ("assent to", "agree to"),
    ("assign to", "allocate to"),
    ("associate with", "connect with"),
    ("attach importance to", "emphasize"),
    ("attend to", "deal with"),
    ("attribute importance to", "value highly"),
    ("avail oneself of", "make use of"),
    ("back up", "support"),
    ("bargain for", "expect"),
    ("base on", "found on"),
    ("bear on", "relate to"),
    ("bear out", "confirm"),
    ("bear with", "tolerate"),
    ("beat about the bush", "avoid the main topic"),
    ("become of", "happen to"),
    ("beg for", "ask earnestly for"),
    ("begin with", "start with"),
    ("believe in", "trust in"),
    ("belong to", "be owned by"),
    ("beware of", "be careful of"),
    ("blame on", "attribute to"),
    ("boast about", "show off"),
    ("border on", "be close to"),
    ("borrow from", "take from"),
    ("bother about", "worry about"),
    ("break away from", "escape from"),
    ("break down", "stop working"),
    ("break into", "enter by force"),
    ("break off", "end"),
    ("break out", "start suddenly"),
    ("break through", "overcome"),
    ("break up", "separate"),
    ("bring forward", "propose"),
    ("bring in", "introduce"),
    ("bring off", "accomplish"),
    ("bring on", "cause"),
    ("bring out", "produce"),
    ("bring up", "raise"),
    ("brush up on", "improve"),
    ("build on", "base on"),
    ("build up", "increase"),
    ("bump into", "meet by chance"),
    ("burst into", "suddenly start"),
    ("buy out", "purchase completely"),
    ("buy up", "purchase all of"),
    ("call at", "visit briefly"),
    ("call off", "cancel"),
    ("call on", "visit"),
    ("call up", "summon"),
    ("care for", "look after"),
    ("carry on", "continue"),
    ("catch on", "become popular"),
    ("catch up", "reach the same level"),
    ("cater for", "provide for"),
    ("change into", "transform into"),
    ("charge with", "accuse of"),
    ("check in", "register"),
    ("check out", "leave"),
    ("cheer up", "become happier"),
    ("clear up", "clarify"),
    ("close down", "shut down"),
    ("come about", "happen"),
    ("come along", "progress"),
    ("come apart", "separate"),
    ("come around", "arrive"),
    ("come back", "return"),
    ("come by", "obtain"),
    ("come down", "decrease"),
    ("come forward", "volunteer"),
    ("come in", "enter"),
    ("come off", "succeed"),
    ("come on", "progress"),
    ("come out", "appear"),
    ("come over", "visit"),
    ("come round", "change opinion"),
    ("come through", "survive"),
    ("come to", "amount to"),
    ("come up", "arise"),
    ("come up against", "encounter"),
    ("compare to", "liken to"),
    ("compare with", "contrast with"),
    ("compete with", "contend with"),
    ("complain about", "express dissatisfaction with"),
    ("conceal from", "hide from"),
    ("concur with", "agree with"),
    ("condemn for", "criticize for"),
    ("confer with", "consult with"),
    ("confess to", "admit to"),
    ("confide in", "trust in"),
    ("conform to", "comply with"),
    ("confront with", "face with"),
    ("congratulate on", "praise for"),
    ("consent to", "agree to"),
    ("consist in", "lie in"),
    ("consist of", "be composed of"),
    ("consult with", "discuss with"),
    ("contend with", "compete with"),
    ("contrast with", "compare with"),
    ("contribute towards", "help to cause"),
    ("convert into", "change into"),
    ("convince of", "persuade of"),
    ("cooperate with", "work together with"),
    ("cope with", "manage successfully"),
    ("correspond to", "match"),
    ("correspond with", "communicate with"),
    ("count on", "rely on"),
    ("cover up", "hide"),
    ("crack down on", "take severe measures against"),
    ("crash into", "collide with"),
    ("credit with", "attribute to"),
    ("cross out", "delete"),
    ("cry out for", "demand urgently"),
    ("cure of", "heal from"),
    ("cut back on", "reduce"),
    ("cut down", "reduce"),
    ("cut off", "disconnect"),
    ("cut out", "remove"),
    ("dash off", "leave quickly"),
    ("dawn on", "become clear to"),
    ("deal in", "trade in"),
    ("deal with", "handle"),
    ("decide on", "choose"),
    ("declare for", "support publicly"),
    ("decline to", "refuse to"),
    ("dedicate to", "devote to"),
    ("deduce from", "infer from"),
    ("defend against", "protect from"),
    ("defer to", "yield to"),
    ("deflect from", "divert from"),
    ("demand from", "request from"),
    ("depart from", "leave"),
    ("depend upon", "rely upon"),
    ("deprive of", "take away from"),
    ("derive from", "originate from"),
    ("descend from", "originate from"),
    ("despair of", "lose hope of"),
    ("deter from", "discourage from"),
    ("deviate from", "divert from")
]

# Write to ts file
with open('src/data/ieltsPhrases.ts', 'w') as f:
    f.write('export type PhrasePair = {\n')
    f.write('  id: string;\n')
    f.write('  phrase1: string;\n')
    f.write('  phrase2: string;\n')
    f.write('};\n\n')
    f.write('export const IELTS_PHRASES: PhrasePair[] = [\n')
    for i, (p1, p2) in enumerate(phrases):
        f.write(f'  {{ id: "{i+1}", phrase1: "{p1}", phrase2: "{p2}" }},\n')
    f.write('];\n')

