import json

data = [
    ("a great deal of", "a lot of", "a large quantity of something", "大量的", ["A great deal of research has been conducted on climate change.", "The new policy will save a lot of time and resources.", "She spent a great deal of money on her IELTS preparation."]),
    ("account for", "explain", "to form the total of something; to explain the reason for something", "占据（比例）；解释...的原因", ["Renewable energy sources account for 30% of the country's electricity.", "The government needs to explain the recent increase in taxes.", "He was unable to account for his absence during the meeting."]),
    ("a wide range of", "a large variety of", "many different types of things or people", "广泛的；多种多样的", ["The library offers a wide range of academic journals.", "A large variety of species can be found in this ecosystem.", "Students can choose from a wide range of extracurricular activities."]),
    ("adapt to", "get used to", "to change your behavior in order to deal more successfully with a new situation", "适应", ["International students often take time to adapt to a new culture.", "It is crucial to get used to the fast-paced working environment.", "Animals must adapt to their changing habitats to survive."]),
    ("adhere to", "stick to", "to continue to obey a rule or have a belief", "坚持；遵守", ["All candidates must adhere to the examination rules.", "It is important to stick to your original study plan.", "The company adheres to strict environmental standards."]),
    ("agree with", "consent to", "to have the same opinion as someone else", "同意；赞同", ["I completely agree with the author's perspective on education.", "The committee consented to the proposed changes.", "Not everyone will agree with this controversial policy."]),
    ("apart from", "except for", "not considering or including", "除了...之外", ["Apart from the high cost, the project is highly feasible.", "Except for a few minor errors, the essay is well-written.", "Apart from English, she is also fluent in French and Spanish."]),
    ("apply for", "request", "to make a formal request, usually in writing", "申请；请求", ["Many graduates apply for jobs in multinational corporations.", "You need to request permission before using the laboratory.", "He decided to apply for a scholarship to study abroad."]),
    ("as a result of", "due to", "because of something", "由于；作为...的结果", ["As a result of the heavy rain, the flight was delayed.", "The business failed due to poor management.", "Many species are endangered as a result of habitat loss."]),
    ("as well as", "in addition to", "and also", "也；以及", ["The course covers literature as well as history.", "In addition to his salary, he receives a performance bonus.", "She is a talented musician as well as a brilliant scientist."]),
    ("at the expense of", "at the cost of", "resulting in the loss of something", "以...为代价", ["Economic development should not come at the expense of the environment.", "He worked hard at the cost of his health.", "The company expanded at the expense of its competitors."]),
    ("attribute to", "ascribe to", "to say or believe that something is the result of a particular thing", "归因于", ["The success of the project can be attributed to teamwork.", "His health issues were ascribed to a lack of exercise.", "She attributes her excellent grades to consistent study."]),
    ("be capable of", "be able to", "having the ability or qualities necessary for doing something", "有能力做...", ["The new software is capable of processing large amounts of data.", "Students should be able to think critically.", "He is capable of speaking four languages fluently."]),
    ("be composed of", "consist of", "to be formed from various things", "由...组成", ["The committee is composed of experts from different fields.", "Water consists of hydrogen and oxygen.", "The exam consists of four different sections."]),
    ("be concerned with", "be related to", "to be about a particular thing or subject", "与...有关；关注", ["This chapter is concerned with the effects of pollution.", "The study is closely related to previous research.", "Environmentalists are concerned with global warming."]),
    ("be dependent on", "rely on", "needing someone or something in order to survive or be successful", "依赖于", ["The local economy is heavily dependent on tourism.", "Many people rely on public transportation to commute.", "Children are dependent on their parents for support."]),
    ("be derived from", "stem from", "to come or develop from something", "源于；来自", ["Many English words are derived from Latin.", "His fear of dogs stems from a childhood incident.", "The concept is derived from ancient philosophy."]),
    ("be eager to", "be anxious to", "wanting very much to do or have something", "渴望做...", ["The students are eager to learn new skills.", "She was anxious to finish the project on time.", "Investors are eager to see the company's financial report."]),
    ("be engaged in", "be involved in", "to be doing or to become involved in an activity", "参与；从事于", ["The two countries are engaged in a trade dispute.", "Many volunteers are involved in the community project.", "He is actively engaged in scientific research."]),
    ("be equivalent to", "be equal to", "having the same amount, value, purpose, qualities, etc.", "等同于；相当于", ["One kilometer is equivalent to 1000 meters.", "The new qualification is equal to a university degree.", "His silence is equivalent to an admission of guilt."]),
    ("be essential for", "be vital for", "completely necessary", "对...至关重要", ["Good nutrition is essential for healthy growth.", "Water is vital for all living organisms.", "Effective communication is essential for teamwork."]),
    ("be exposed to", "be subjected to", "to be put in a situation where something might affect you", "暴露于；遭受", ["Children exposed to music early tend to develop better cognitive skills.", "The materials were subjected to high temperatures.", "Workers should not be exposed to toxic chemicals."]),
    ("be familiar with", "be acquainted with", "knowing something quite well", "熟悉", ["Applicants must be familiar with computer programming.", "I am not acquainted with the new regulations.", "Students should be familiar with the exam format."]),
    ("be forced to", "be compelled to", "to make someone do something they do not want to do", "被迫做...", ["The company was forced to close down due to bankruptcy.", "He felt compelled to resign from his position.", "Many residents were forced to evacuate the area."]),
    ("be identical to", "be the same as", "exactly the same", "与...完全相同", ["Her dress is identical to mine.", "The results of the two experiments are the same as each other.", "The new model is almost identical to the previous one."]),
    ("be ignorant of", "be unaware of", "not knowing about something", "对...无知；不知道", ["Many consumers are ignorant of their legal rights.", "He was unaware of the changes in the schedule.", "Being ignorant of the law is no excuse."]),
    ("be inclined to", "tend to", "to be likely to do something", "倾向于", ["People are inclined to believe what they see.", "Prices tend to rise during the holiday season.", "I am inclined to agree with your proposal."]),
    ("be indifferent to", "turn a blind eye to", "not caring about something", "对...漠不关心", ["The government cannot be indifferent to the housing crisis.", "We should not turn a blind eye to environmental issues.", "He seemed indifferent to the suffering of others."]),
    ("be indispensable for", "be crucial for", "too important to be without", "必不可少的", ["A good dictionary is indispensable for learning a language.", "Teamwork is crucial for the success of the project.", "Air and water are indispensable for life."]),
    ("be inferior to", "be worse than", "not as good as someone or something else", "不如...；劣于", ["The quality of this product is inferior to that of the original.", "This year's harvest is worse than last year's.", "He felt inferior to his older brother."]),
    ("be liable to", "be prone to", "likely to do or be affected by something", "易于...的", ["The area is liable to flooding during the rainy season.", "Older people are more prone to certain diseases.", "He is liable to make mistakes when tired."]),
    ("be linked to", "be associated with", "to be connected with something", "与...有关联", ["The disease is closely linked to poor diet.", "High stress levels are associated with heart problems.", "Crime rates are often linked to unemployment."]),
    ("be opposed to", "be against", "disagreeing strongly with something", "反对", ["Many residents are opposed to the construction of the new highway.", "The organization is against animal testing.", "He is strongly opposed to the new tax policy."]),
    ("be prior to", "be before", "happening or existing before something else", "在...之前", ["The contract must be signed prior to the start of the work.", "Please arrive at least 15 minutes before the interview.", "The event occurred prior to World War II."]),
    ("be reluctant to", "be unwilling to", "hesitating before doing something", "不情愿做...", ["She was reluctant to accept the offer.", "Many employees are unwilling to work overtime.", "He was reluctant to admit his mistake."]),
    ("be responsible for", "be in charge of", "having control and authority over something", "负责...", ["The manager is responsible for the daily operations.", "She is in charge of the marketing department.", "Parents are responsible for their children's behavior."]),
    ("be restricted to", "be limited to", "kept within certain limits", "局限于", ["Access to this facility is restricted to authorized personnel.", "The discussion will be limited to academic topics.", "The disease is mainly restricted to tropical regions."]),
    ("be satisfied with", "be content with", "pleased because you have achieved something", "对...感到满意", ["The customers were highly satisfied with the service.", "He is content with his simple life.", "We are not satisfied with the current progress."]),
    ("be sensitive to", "be susceptible to", "easily affected or damaged by something", "对...敏感；易受...影响", ["Some people are highly sensitive to changes in temperature.", "Children are more susceptible to infections.", "The economy is sensitive to political instability."]),
    ("be similar to", "be akin to", "like somebody or something but not exactly the same", "与...相似", ["The new design is very similar to the old one.", "His writing style is akin to that of classical authors.", "The two languages are quite similar to each other."]),
    ("be subject to", "be vulnerable to", "likely to experience or suffer from something", "易遭受...的", ["Flights are subject to delay due to bad weather.", "The city is vulnerable to earthquakes.", "Prices are subject to change without notice."]),
    ("be superior to", "be better than", "better in quality than somebody or something else", "优于；比...更好", ["The new technology is vastly superior to the old system.", "This product is better than anything else on the market.", "Her performance was superior to the rest of the team."]),
    ("be supposed to", "be expected to", "to be intended to", "应该...；被期望...", ["You are supposed to submit the report by Friday.", "The train is expected to arrive at 9 AM.", "Students are supposed to complete their assignments independently."]),
    ("be suspicious of", "be skeptical of", "feeling that somebody has done something wrong", "对...持怀疑态度", ["The police were suspicious of his behavior.", "Many scientists are skeptical of the new theory.", "Consumers are increasingly suspicious of online advertisements."]),
    ("be typical of", "be characteristic of", "having the usual qualities or features of a particular type", "是...的典型", ["This mild weather is typical of the region in autumn.", "Such behavior is characteristic of young children.", "The painting is typical of his early work."]),
    ("be used to", "be accustomed to", "familiar with something", "习惯于", ["I am used to waking up early in the morning.", "She quickly became accustomed to the new environment.", "It takes time to get used to living in a foreign country."]),
    ("be willing to", "be ready to", "happy or prepared to do something", "愿意做...", ["The company is willing to invest in new technologies.", "He is always ready to help his colleagues.", "Are you willing to take on more responsibilities?"]),
    ("bear in mind", "keep in mind", "to remember a piece of information when making a decision", "记住", ["Bear in mind that the deadline is approaching.", "Keep in mind the importance of regular exercise.", "You must bear in mind the potential risks."]),
    ("benefit from", "profit from", "to receive an advantage", "从...中获益", ["Students will greatly benefit from the new library facilities.", "The company profited from the recent surge in demand.", "Many patients have benefited from this treatment."]),
    ("blame for", "hold responsible for", "to say that someone is responsible for something bad", "责备；让...负责", ["He was blamed for the failure of the project.", "The government is held responsible for the economic crisis.", "Don't blame others for your own mistakes."]),
    ("bring about", "lead to", "to make something happen", "引起；导致", ["The new policy brought about significant changes in the industry.", "Poor diet can lead to serious health problems.", "The invention of the internet brought about a revolution in communication."]),
    ("by means of", "by way of", "using a particular method or system", "通过...方式", ["The load was lifted by means of a crane.", "They communicated by way of sign language.", "The problem was solved by means of negotiation."]),
    ("by no means", "in no way", "not at all", "绝不", ["The issue is by no means resolved.", "This is in no way an easy task.", "The results are by no means guaranteed."]),
    ("call for", "require", "to need something", "需要；呼吁", ["The situation calls for immediate action.", "This job requires a high level of concentration.", "The protesters are calling for stricter environmental laws."]),
    ("carry out", "implement", "to do and complete a task", "执行；实施", ["The scientists carried out a series of experiments.", "The government plans to implement the new policy next year.", "It is difficult to carry out the plan without sufficient funding."]),
    ("catch up with", "keep pace with", "to reach the same level or standard", "赶上", ["He had to work hard to catch up with his classmates.", "It is challenging to keep pace with technological advancements.", "The company is struggling to catch up with its competitors."]),
    ("come across", "run into", "to meet or find by chance", "偶然遇见；偶然发现", ["I came across an interesting article in the newspaper.", "She ran into an old friend at the supermarket.", "Researchers came across a rare species of bird."]),
    ("come up with", "think of", "to suggest or think of an idea or plan", "想出；提出", ["The team came up with a brilliant marketing strategy.", "Can you think of a better solution?", "He came up with a new method to reduce waste."]),
    ("comment on", "remark on", "to express an opinion about something", "评论", ["The professor commented on the student's essay.", "She remarked on the beautiful architecture of the building.", "The spokesperson declined to comment on the rumors."]),
    ("compensate for", "make up for", "to provide something good to balance something bad", "补偿；弥补", ["The company compensated him for his extra working hours.", "Nothing can make up for the loss of a loved one.", "He bought her flowers to compensate for being late."]),
    ("comply with", "conform to", "to obey a rule or order", "遵守；符合", ["All products must comply with safety regulations.", "The building design conforms to the local architectural style.", "Failure to comply with the rules will result in a penalty."]),
    ("concentrate on", "focus on", "to give all your attention to something", "集中注意力于", ["You should concentrate on your studies.", "The report focuses on the impact of climate change.", "It is hard to concentrate on work with so much noise."]),
    ("contribute to", "play a part in", "to help to cause an event or situation", "促成；有助于", ["Air pollution contributes to global warming.", "Diet plays a significant part in overall health.", "His hard work contributed to the success of the project."]),
    ("cope with", "deal with", "to deal successfully with a difficult situation", "处理；应付", ["She has a lot of stress to cope with at work.", "The government must deal with the rising unemployment rate.", "He learned how to cope with anxiety."]),
    ("cut down on", "reduce", "to do or use less of something", "减少", ["You should cut down on sugary foods to stay healthy.", "The factory has reduced its carbon emissions by 20%.", "Cutting down on expenses is necessary for the company."]),
    ("date back to", "originate from", "to have existed since a particular time", "追溯到；起源于", ["The castle dates back to the 15th century.", "Many English words originate from Latin and Greek.", "This tradition dates back to ancient times."]),
    ("depend on", "rely on", "to trust someone or something", "依赖；依靠", ["The success of the event depends on the weather.", "Many people rely on the internet for information.", "You can always depend on him for help."]),
    ("deprive of", "strip of", "to take something important away from someone", "剥夺", ["The prisoners were deprived of their basic rights.", "He was stripped of his title after the scandal.", "Lack of sleep deprives the brain of essential rest."]),
    ("devote to", "dedicate to", "to give most of your time or energy to something", "致力于", ["She devoted her life to helping the poor.", "The organization is dedicated to protecting wildlife.", "He devoted a lot of time to his research."]),
    ("die out", "become extinct", "to stop existing", "灭绝；消失", ["Many traditional skills are in danger of dying out.", "Dinosaurs became extinct millions of years ago.", "If we don't protect them, these animals will die out."]),
    ("differ from", "be distinct from", "to be different", "与...不同", ["His opinion differs significantly from mine.", "This species is distinct from others in the region.", "The two cultures differ from each other in many ways."]),
    ("dispose of", "get rid of", "to throw away or destroy", "处理；丢弃", ["It is important to dispose of hazardous waste properly.", "He decided to get rid of his old car.", "The city needs a better way to dispose of garbage."]),
    ("distinguish between", "differentiate between", "to recognize the difference between two things", "区分；辨别", ["It is difficult to distinguish between the twin brothers.", "You must learn to differentiate between fact and opinion.", "Color-blind people cannot distinguish between red and green."]),
    ("do away with", "eliminate", "to remove or put an end to something", "废除；消除", ["The company decided to do away with the old dress code.", "The new policy aims to eliminate poverty.", "We should do away with unnecessary paperwork."]),
    ("draw attention to", "highlight", "to make people notice something", "引起对...的注意；强调", ["The report draws attention to the issue of child labor.", "The speaker highlighted the importance of education.", "The incident drew public attention to safety regulations."]),
    ("drop out of", "quit", "to leave school or a course before finishing", "辍学；退出", ["He dropped out of college to start his own business.", "She quit her job to travel the world.", "Many students drop out of school due to financial problems."]),
    ("due to", "because of", "caused by or ascribable to", "由于", ["The flight was canceled due to bad weather.", "He succeeded because of his hard work.", "The delay was due to a technical issue."]),
    ("embark on", "start", "to begin a new project or journey", "开始；着手", ["She is about to embark on a new career in marketing.", "They started their journey early in the morning.", "The government embarked on a major reform program."]),
    ("end up with", "result in", "to finally be in a particular situation or state", "最终导致；以...结束", ["If you don't study, you will end up with a low grade.", "The negotiations resulted in a peace treaty.", "He ended up with a huge debt."]),
    ("engage in", "participate in", "to take part in an activity", "参与；从事", ["Students are encouraged to engage in extracurricular activities.", "Many people participated in the marathon.", "He was actively engaged in local politics."]),
    ("exert influence on", "have an impact on", "to affect someone or something", "对...施加影响", ["Parents exert a strong influence on their children's behavior.", "Technology has a profound impact on modern society.", "The media exerts a significant influence on public opinion."]),
    ("fall short of", "fail to reach", "to fail to meet an expectation or standard", "未达到；不符合", ["The company's profits fell short of expectations.", "He failed to reach his sales target this month.", "The performance fell short of the audience's hopes."]),
    ("figure out", "work out", "to understand or solve something", "弄清楚；解决", ["It took me hours to figure out the math problem.", "They are trying to work out a new schedule.", "We need to figure out a way to reduce costs."]),
    ("focus on", "concentrate on", "to give a lot of attention to one particular person, subject, or thing", "专注于", ["The meeting will focus on environmental issues.", "You need to concentrate on your driving.", "The study focuses on the effects of sleep deprivation."]),
    ("for the sake of", "for the benefit of", "in order to help or bring advantage to someone", "为了...的利益", ["He moved to the countryside for the sake of his health.", "The charity works for the benefit of homeless children.", "She compromised for the sake of peace."]),
    ("get access to", "gain entry to", "to obtain the right or opportunity to use something", "获得...的途径", ["Students can get access to the library's online resources.", "He gained entry to the exclusive club.", "It is difficult to get access to clean water in some areas."]),
    ("get accustomed to", "get used to", "to become familiar with something", "习惯于", ["It takes time to get accustomed to the local food.", "She quickly got used to the cold weather.", "He is getting accustomed to his new job."]),
    ("get along with", "get on with", "to have a friendly relationship with someone", "与...和睦相处", ["She gets along well with all her colleagues.", "He doesn't get on with his neighbors.", "It is important to get along with your teammates."]),
    ("give priority to", "put first", "to deal with something first because it is the most important", "优先考虑", ["The hospital gives priority to emergency cases.", "You should put your family first.", "The government is giving priority to education reform."]),
    ("give rise to", "cause", "to make something happen or begin", "引起；导致", ["The new tax policy gave rise to widespread protests.", "Smoking can cause serious health issues.", "The misunderstanding gave rise to a conflict."]),
    ("go hand in hand with", "be closely connected with", "to happen or exist together", "与...密切相关", ["Economic growth often goes hand in hand with environmental damage.", "Poverty is closely connected with poor health.", "Wealth and power usually go hand in hand."]),
    ("have a negative impact on", "take a toll on", "to affect something badly", "对...产生负面影响", ["Pollution has a negative impact on public health.", "The stress of the job took a toll on his mental health.", "Lack of sleep has a negative impact on academic performance."]),
    ("have an effect on", "influence", "to produce a change in somebody or something", "对...有影响", ["The weather has a significant effect on crop yields.", "His parents greatly influenced his career choice.", "Social media has a profound effect on teenagers."]),
    ("have nothing to do with", "be irrelevant to", "to not involve or be connected with", "与...无关", ["His decision has nothing to do with money.", "This evidence is irrelevant to the case.", "The rumor has nothing to do with the truth."]),
    ("in accordance with", "in line with", "according to a rule or the way that somebody says that something should be done", "依照；与...一致", ["The project was completed in accordance with the contract.", "His actions are in line with company policy.", "The building was designed in accordance with safety standards."]),
    ("in advance", "beforehand", "before the time that is expected", "提前", ["You need to book the tickets in advance.", "Please let me know beforehand if you cannot attend.", "Payment must be made in advance."]),
    ("in charge of", "responsible for", "having control or command of", "负责", ["He is in charge of the marketing department.", "She is responsible for organizing the event.", "Who is in charge of this project?"]),
    ("in comparison with", "compared to", "when compared with", "与...相比", ["In comparison with last year, profits have increased by 20%.", "Compared to city life, the countryside is much quieter.", "His performance was excellent in comparison with his peers."]),
    ("in conflict with", "at odds with", "in opposition to", "与...冲突", ["His statement is in conflict with the evidence.", "The two brothers are always at odds with each other.", "The new law is in conflict with human rights."]),
    ("in connection with", "in relation to", "concerning or involving", "与...有关", ["A man was arrested in connection with the robbery.", "I am writing in relation to your job advertisement.", "The meeting was held in connection with the recent changes."])
]

with open('src/data/ieltsPhrases.ts', 'w') as f:
    f.write('export type PhrasePair = {\n')
    f.write('  id: string;\n')
    f.write('  phrase1: string;\n')
    f.write('  phrase2: string;\n')
    f.write('  meaningEn: string;\n')
    f.write('  meaningZh: string;\n')
    f.write('  examples: string[];\n')
    f.write('};\n\n')
    f.write('export const IELTS_PHRASES: PhrasePair[] = [\n')
    for i, item in enumerate(data):
        f.write(f'  {{\n')
        f.write(f'    id: "{i+1}",\n')
        f.write(f'    phrase1: "{item[0]}",\n')
        f.write(f'    phrase2: "{item[1]}",\n')
        f.write(f'    meaningEn: "{item[2]}",\n')
        f.write(f'    meaningZh: "{item[3]}",\n')
        f.write(f'    examples: {json.dumps(item[4], ensure_ascii=False)}\n')
        f.write(f'  }},\n')
    f.write('];\n')

